// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/register_request.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_model_register_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_register_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_model_register_request_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

var File_model_register_request_proto protoreflect.FileDescriptor

const file_model_register_request_proto_rawDesc = "" +
	"\n" +
	"\x1cmodel/register_request.proto\x12\x17keeper.go.grpc.v1.model\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB Z\x1ekeeper/internal/proto/v1/modelb\beditionsp\xe8\a"

var (
	file_model_register_request_proto_rawDescOnce sync.Once
	file_model_register_request_proto_rawDescData []byte
)

func file_model_register_request_proto_rawDescGZIP() []byte {
	file_model_register_request_proto_rawDescOnce.Do(func() {
		file_model_register_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_register_request_proto_rawDesc), len(file_model_register_request_proto_rawDesc)))
	})
	return file_model_register_request_proto_rawDescData
}

var file_model_register_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_register_request_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: keeper.go.grpc.v1.model.RegisterRequest
}
var file_model_register_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_register_request_proto_init() }
func file_model_register_request_proto_init() {
	if File_model_register_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_register_request_proto_rawDesc), len(file_model_register_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_register_request_proto_goTypes,
		DependencyIndexes: file_model_register_request_proto_depIdxs,
		MessageInfos:      file_model_register_request_proto_msgTypes,
	}.Build()
	File_model_register_request_proto = out.File
	file_model_register_request_proto_goTypes = nil
	file_model_register_request_proto_depIdxs = nil
}
