// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/secret.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Path          *string                `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt" json:"expired_at,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecret) Reset() {
	*x = WriteSecret{}
	mi := &file_model_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecret) ProtoMessage() {}

func (x *WriteSecret) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecret.ProtoReflect.Descriptor instead.
func (*WriteSecret) Descriptor() ([]byte, []int) {
	return file_model_secret_proto_rawDescGZIP(), []int{0}
}

func (x *WriteSecret) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *WriteSecret) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *WriteSecret) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *WriteSecret) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *WriteSecret) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SaveSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSecretResponse) Reset() {
	*x = SaveSecretResponse{}
	mi := &file_model_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSecretResponse) ProtoMessage() {}

func (x *SaveSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSecretResponse.ProtoReflect.Descriptor instead.
func (*SaveSecretResponse) Descriptor() ([]byte, []int) {
	return file_model_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SaveSecretResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *SaveSecretResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type SecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt" json:"expired_at,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Version       *int64                 `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_model_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretResponse.ProtoReflect.Descriptor instead.
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return file_model_secret_proto_rawDescGZIP(), []int{2}
}

func (x *SecretResponse) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *SecretResponse) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *SecretResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SecretResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SecretResponse) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SecretResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *SecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_model_secret_proto protoreflect.FileDescriptor

const file_model_secret_proto_rawDesc = "" +
	"\n" +
	"\x12model/secret.proto\x12\x17keeper.go.grpc.v1.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\vWriteSecret\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"H\n" +
	"\x12SaveSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa7\x02\n" +
	"\x0eSecretResponse\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB Z\x1ekeeper/internal/proto/v1/modelb\beditionsp\xe8\a"

var (
	file_model_secret_proto_rawDescOnce sync.Once
	file_model_secret_proto_rawDescData []byte
)

func file_model_secret_proto_rawDescGZIP() []byte {
	file_model_secret_proto_rawDescOnce.Do(func() {
		file_model_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_secret_proto_rawDesc), len(file_model_secret_proto_rawDesc)))
	})
	return file_model_secret_proto_rawDescData
}

var file_model_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_secret_proto_goTypes = []any{
	(*WriteSecret)(nil),           // 0: keeper.go.grpc.v1.model.WriteSecret
	(*SaveSecretResponse)(nil),    // 1: keeper.go.grpc.v1.model.SaveSecretResponse
	(*SecretResponse)(nil),        // 2: keeper.go.grpc.v1.model.SecretResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_model_secret_proto_depIdxs = []int32{
	3, // 0: keeper.go.grpc.v1.model.WriteSecret.expired_at:type_name -> google.protobuf.Timestamp
	3, // 1: keeper.go.grpc.v1.model.SecretResponse.expired_at:type_name -> google.protobuf.Timestamp
	3, // 2: keeper.go.grpc.v1.model.SecretResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 3: keeper.go.grpc.v1.model.SecretResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_secret_proto_init() }
func file_model_secret_proto_init() {
	if File_model_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_secret_proto_rawDesc), len(file_model_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_secret_proto_goTypes,
		DependencyIndexes: file_model_secret_proto_depIdxs,
		MessageInfos:      file_model_secret_proto_msgTypes,
	}.Build()
	File_model_secret_proto = out.File
	file_model_secret_proto_goTypes = nil
	file_model_secret_proto_depIdxs = nil
}
