// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/secret.proto

package model

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteSecret struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_Path        *string                `protobuf:"bytes,2,opt,name=path"`
	xxx_hidden_ExpiredAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Value       []byte                 `protobuf:"bytes,5,opt,name=value"`
	xxx_hidden_FilePath    *string                `protobuf:"bytes,6,opt,name=file_path,json=filePath"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WriteSecret) Reset() {
	*x = WriteSecret{}
	mi := &file_model_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecret) ProtoMessage() {}

func (x *WriteSecret) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteSecret) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *WriteSecret) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *WriteSecret) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiredAt
	}
	return nil
}

func (x *WriteSecret) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *WriteSecret) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *WriteSecret) GetFilePath() string {
	if x != nil {
		if x.xxx_hidden_FilePath != nil {
			return *x.xxx_hidden_FilePath
		}
		return ""
	}
	return ""
}

func (x *WriteSecret) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *WriteSecret) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *WriteSecret) SetExpiredAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiredAt = v
}

func (x *WriteSecret) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *WriteSecret) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *WriteSecret) SetFilePath(v string) {
	x.xxx_hidden_FilePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *WriteSecret) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WriteSecret) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *WriteSecret) HasExpiredAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiredAt != nil
}

func (x *WriteSecret) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *WriteSecret) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *WriteSecret) HasFilePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *WriteSecret) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *WriteSecret) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Path = nil
}

func (x *WriteSecret) ClearExpiredAt() {
	x.xxx_hidden_ExpiredAt = nil
}

func (x *WriteSecret) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *WriteSecret) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Value = nil
}

func (x *WriteSecret) ClearFilePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_FilePath = nil
}

type WriteSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token       *string
	Path        *string
	ExpiredAt   *timestamppb.Timestamp
	Description *string
	Value       []byte
	FilePath    *string
}

func (b0 WriteSecret_builder) Build() *WriteSecret {
	m0 := &WriteSecret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Token = b.Token
	}
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Path = b.Path
	}
	x.xxx_hidden_ExpiredAt = b.ExpiredAt
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Value = b.Value
	}
	if b.FilePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_FilePath = b.FilePath
	}
	return m0
}

type SaveSecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SaveSecretResponse) Reset() {
	*x = SaveSecretResponse{}
	mi := &file_model_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSecretResponse) ProtoMessage() {}

func (x *SaveSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *SaveSecretResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *SaveSecretResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SaveSecretResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SaveSecretResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SaveSecretResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SaveSecretResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *SaveSecretResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type SaveSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
	Message *string
}

func (b0 SaveSecretResponse_builder) Build() *SaveSecretResponse {
	m0 := &SaveSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Success = *b.Success
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type SecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,2,opt,name=path"`
	xxx_hidden_ExpiredAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Value       []byte                 `protobuf:"bytes,5,opt,name=value"`
	xxx_hidden_Version     int64                  `protobuf:"varint,6,opt,name=version"`
	xxx_hidden_DeletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt"`
	xxx_hidden_FilePath    *string                `protobuf:"bytes,9,opt,name=file_path,json=filePath"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_model_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretResponse) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiredAt
	}
	return nil
}

func (x *SecretResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *SecretResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *SecretResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *SecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SecretResponse) GetFilePath() string {
	if x != nil {
		if x.xxx_hidden_FilePath != nil {
			return *x.xxx_hidden_FilePath
		}
		return ""
	}
	return ""
}

func (x *SecretResponse) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *SecretResponse) SetExpiredAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiredAt = v
}

func (x *SecretResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *SecretResponse) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *SecretResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *SecretResponse) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *SecretResponse) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretResponse) SetFilePath(v string) {
	x.xxx_hidden_FilePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *SecretResponse) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretResponse) HasExpiredAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiredAt != nil
}

func (x *SecretResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SecretResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SecretResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SecretResponse) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *SecretResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SecretResponse) HasFilePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *SecretResponse) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

func (x *SecretResponse) ClearExpiredAt() {
	x.xxx_hidden_ExpiredAt = nil
}

func (x *SecretResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *SecretResponse) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Value = nil
}

func (x *SecretResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

func (x *SecretResponse) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

func (x *SecretResponse) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *SecretResponse) ClearFilePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_FilePath = nil
}

type SecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path        *string
	ExpiredAt   *timestamppb.Timestamp
	Description *string
	Value       []byte
	Version     *int64
	DeletedAt   *timestamppb.Timestamp
	CreatedAt   *timestamppb.Timestamp
	FilePath    *string
}

func (b0 SecretResponse_builder) Build() *SecretResponse {
	m0 := &SecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Path = b.Path
	}
	x.xxx_hidden_ExpiredAt = b.ExpiredAt
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Description = b.Description
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Value = b.Value
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_DeletedAt = b.DeletedAt
	x.xxx_hidden_CreatedAt = b.CreatedAt
	if b.FilePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_FilePath = b.FilePath
	}
	return m0
}

var File_model_secret_proto protoreflect.FileDescriptor

const file_model_secret_proto_rawDesc = "" +
	"\n" +
	"\x12model/secret.proto\x12\x17keeper.go.grpc.v1.model\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\xc7\x01\n" +
	"\vWriteSecret\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x1b\n" +
	"\tfile_path\x18\x06 \x01(\tR\bfilePath\"H\n" +
	"\x12SaveSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x02\n" +
	"\x0eSecretResponse\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tfile_path\x18\t \x01(\tR\bfilePathB(Z\x1ekeeper/internal/proto/v1/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_model_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_secret_proto_goTypes = []any{
	(*WriteSecret)(nil),           // 0: keeper.go.grpc.v1.model.WriteSecret
	(*SaveSecretResponse)(nil),    // 1: keeper.go.grpc.v1.model.SaveSecretResponse
	(*SecretResponse)(nil),        // 2: keeper.go.grpc.v1.model.SecretResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_model_secret_proto_depIdxs = []int32{
	3, // 0: keeper.go.grpc.v1.model.WriteSecret.expired_at:type_name -> google.protobuf.Timestamp
	3, // 1: keeper.go.grpc.v1.model.SecretResponse.expired_at:type_name -> google.protobuf.Timestamp
	3, // 2: keeper.go.grpc.v1.model.SecretResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 3: keeper.go.grpc.v1.model.SecretResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_secret_proto_init() }
func file_model_secret_proto_init() {
	if File_model_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_secret_proto_rawDesc), len(file_model_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_secret_proto_goTypes,
		DependencyIndexes: file_model_secret_proto_depIdxs,
		MessageInfos:      file_model_secret_proto_msgTypes,
	}.Build()
	File_model_secret_proto = out.File
	file_model_secret_proto_goTypes = nil
	file_model_secret_proto_depIdxs = nil
}
