BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS secrets (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    description TEXT,
    version INTEGER NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    destroyed BOOLEAN DEFAULT FALSE,
    UNIQUE(user_id, title)
);

COMMIT;