// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package v1

import (
	model "keeper/internal/proto/v1/model"
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x11keeper.go.grpc.v1\x1a\x14model/register.proto\x1a\x11model/login.proto\x1a!google/protobuf/go_features.proto\x1a\x12model/secret.proto\x1a\x16model/get_secret.proto\x1a\x19model/delete_secret.proto\x1a\x18model/list_secrets.proto\x1a\x12model/upload.proto2\xc6\x01\n" +
	"\vAuthService\x12_\n" +
	"\bRegister\x12(.keeper.go.grpc.v1.model.RegisterRequest\x1a).keeper.go.grpc.v1.model.RegisterResponse\x12V\n" +
	"\x05Login\x12%.keeper.go.grpc.v1.model.LoginRequest\x1a&.keeper.go.grpc.v1.model.LoginResponse2\xfc\x05\n" +
	"\vDataService\x12_\n" +
	"\tGetSecret\x12).keeper.go.grpc.v1.model.GetSecretRequest\x1a'.keeper.go.grpc.v1.model.SecretResponse\x12p\n" +
	"\vListSecrets\x12/.keeper.go.grpc.v1.model.ListSecretPathsRequest\x1a0.keeper.go.grpc.v1.model.ListSecretPathsResponse\x12_\n" +
	"\n" +
	"SaveSecret\x12$.keeper.go.grpc.v1.model.WriteSecret\x1a+.keeper.go.grpc.v1.model.SaveSecretResponse\x12k\n" +
	"\fDeleteSecret\x12,.keeper.go.grpc.v1.model.DeleteSecretRequest\x1a-.keeper.go.grpc.v1.model.DeleteSecretResponse\x12l\n" +
	"\rDestroySecret\x12,.keeper.go.grpc.v1.model.DeleteSecretRequest\x1a-.keeper.go.grpc.v1.model.DeleteSecretResponse\x12m\n" +
	"\x0eDeleteMetadata\x12,.keeper.go.grpc.v1.model.DeleteSecretRequest\x1a-.keeper.go.grpc.v1.model.DeleteSecretResponse\x12o\n" +
	"\x0eUndeleteSecret\x12..keeper.go.grpc.v1.model.UndeleteSecretRequest\x1a-.keeper.go.grpc.v1.model.DeleteSecretResponse2t\n" +
	"\vFileService\x12e\n" +
	"\n" +
	"UploadFile\x12*.keeper.go.grpc.v1.model.UploadFileRequest\x1a+.keeper.go.grpc.v1.model.UploadFileResponseB\"Z\x18keeper/internal/proto/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_service_proto_goTypes = []any{
	(*model.RegisterRequest)(nil),         // 0: keeper.go.grpc.v1.model.RegisterRequest
	(*model.LoginRequest)(nil),            // 1: keeper.go.grpc.v1.model.LoginRequest
	(*model.GetSecretRequest)(nil),        // 2: keeper.go.grpc.v1.model.GetSecretRequest
	(*model.ListSecretPathsRequest)(nil),  // 3: keeper.go.grpc.v1.model.ListSecretPathsRequest
	(*model.WriteSecret)(nil),             // 4: keeper.go.grpc.v1.model.WriteSecret
	(*model.DeleteSecretRequest)(nil),     // 5: keeper.go.grpc.v1.model.DeleteSecretRequest
	(*model.UndeleteSecretRequest)(nil),   // 6: keeper.go.grpc.v1.model.UndeleteSecretRequest
	(*model.UploadFileRequest)(nil),       // 7: keeper.go.grpc.v1.model.UploadFileRequest
	(*model.RegisterResponse)(nil),        // 8: keeper.go.grpc.v1.model.RegisterResponse
	(*model.LoginResponse)(nil),           // 9: keeper.go.grpc.v1.model.LoginResponse
	(*model.SecretResponse)(nil),          // 10: keeper.go.grpc.v1.model.SecretResponse
	(*model.ListSecretPathsResponse)(nil), // 11: keeper.go.grpc.v1.model.ListSecretPathsResponse
	(*model.SaveSecretResponse)(nil),      // 12: keeper.go.grpc.v1.model.SaveSecretResponse
	(*model.DeleteSecretResponse)(nil),    // 13: keeper.go.grpc.v1.model.DeleteSecretResponse
	(*model.UploadFileResponse)(nil),      // 14: keeper.go.grpc.v1.model.UploadFileResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: keeper.go.grpc.v1.AuthService.Register:input_type -> keeper.go.grpc.v1.model.RegisterRequest
	1,  // 1: keeper.go.grpc.v1.AuthService.Login:input_type -> keeper.go.grpc.v1.model.LoginRequest
	2,  // 2: keeper.go.grpc.v1.DataService.GetSecret:input_type -> keeper.go.grpc.v1.model.GetSecretRequest
	3,  // 3: keeper.go.grpc.v1.DataService.ListSecrets:input_type -> keeper.go.grpc.v1.model.ListSecretPathsRequest
	4,  // 4: keeper.go.grpc.v1.DataService.SaveSecret:input_type -> keeper.go.grpc.v1.model.WriteSecret
	5,  // 5: keeper.go.grpc.v1.DataService.DeleteSecret:input_type -> keeper.go.grpc.v1.model.DeleteSecretRequest
	5,  // 6: keeper.go.grpc.v1.DataService.DestroySecret:input_type -> keeper.go.grpc.v1.model.DeleteSecretRequest
	5,  // 7: keeper.go.grpc.v1.DataService.DeleteMetadata:input_type -> keeper.go.grpc.v1.model.DeleteSecretRequest
	6,  // 8: keeper.go.grpc.v1.DataService.UndeleteSecret:input_type -> keeper.go.grpc.v1.model.UndeleteSecretRequest
	7,  // 9: keeper.go.grpc.v1.FileService.UploadFile:input_type -> keeper.go.grpc.v1.model.UploadFileRequest
	8,  // 10: keeper.go.grpc.v1.AuthService.Register:output_type -> keeper.go.grpc.v1.model.RegisterResponse
	9,  // 11: keeper.go.grpc.v1.AuthService.Login:output_type -> keeper.go.grpc.v1.model.LoginResponse
	10, // 12: keeper.go.grpc.v1.DataService.GetSecret:output_type -> keeper.go.grpc.v1.model.SecretResponse
	11, // 13: keeper.go.grpc.v1.DataService.ListSecrets:output_type -> keeper.go.grpc.v1.model.ListSecretPathsResponse
	12, // 14: keeper.go.grpc.v1.DataService.SaveSecret:output_type -> keeper.go.grpc.v1.model.SaveSecretResponse
	13, // 15: keeper.go.grpc.v1.DataService.DeleteSecret:output_type -> keeper.go.grpc.v1.model.DeleteSecretResponse
	13, // 16: keeper.go.grpc.v1.DataService.DestroySecret:output_type -> keeper.go.grpc.v1.model.DeleteSecretResponse
	13, // 17: keeper.go.grpc.v1.DataService.DeleteMetadata:output_type -> keeper.go.grpc.v1.model.DeleteSecretResponse
	13, // 18: keeper.go.grpc.v1.DataService.UndeleteSecret:output_type -> keeper.go.grpc.v1.model.DeleteSecretResponse
	14, // 19: keeper.go.grpc.v1.FileService.UploadFile:output_type -> keeper.go.grpc.v1.model.UploadFileResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
