name: Go Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out